[package]
description.workspace = true
edition.workspace = true
license.workspace = true
name = "kittynode-cli"
readme.workspace = true
repository.workspace = true
version = "0.4.0"

[[bin]]
name = "kittynode"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
eyre = { version = "0.6.12", default-features = false, features = [
  "auto-install",
  "track-caller",
] }
kittynode-core = { version = "0.4.0", path = "../core" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
